;(function(){'use strict';var fn=MugineRequire("Utils/Module"),gn=MugineRequire("Text/TextField"),hn=MugineRequire("Utils/Plugin");function jn(){jn.j.constructor.apply(this,arguments);this.Ji="";this.qh=this.Tj=null}fn.extend(jn,gn);jn.prototype.I="Text";jn.Eb=function(a,b){function c(){c.j.constructor.apply(this,arguments);this.Ji=f;this.qh=g;var a=this.Md.hd.clone();a.Vt(.4);this.Tj=a;this.Wa("")}var d=gn.Eb(a,b);fn.extend(d,jn);var e=a.param,f=e.textContent,g=e.inputType;fn.extend(c,d);return c};
fn.G("Text.InputBox",jn);hn.Vd(2031,jn);var kn=MugineRequire("Utils/Module"),ln=MugineRequire("Utils/Browser"),mn=MugineRequire("Render/RenderObjectTextField"),nn=MugineRequire("Render/StyleSheet"),on=MugineRequire("Utils/Plugin"),pn=MugineRequire("Render/RenderObject");function qn(){qn.j.constructor.apply(this,arguments)}kn.extend(qn,mn);pn.Na=function(a){return pn.$f[a]};var rn=qn.prototype;
rn.La=function(){var a=this.c,b=this.Fs(),c=a.Md,d=a.u.ta,e="";d.ib&&0<d.ib.ca&&(e+=ln.prefix.f+"text-stroke:"+d.Jb/1+"px "+d.ib.Nb()+";");c=nn.T("position: absolute; outline: none; padding: 0; background: transparent; border-radius: 0; border: 0; width: "+a.ra+"px; height: "+a.qa+"px;"+ln.prefix.f+"transform-origin: left top;"+ln.prefix.f+"appearance:none;"+ln.prefix.f+"user-select: initial;"+e+"font-family: "+c.yj+";text-align: "+c.Mg+";color: "+c.hd.Nb()+";font-size: "+d.wb+"px;"+(c.pj?"font-weight: bold;":
"")+(c.Pl?"text-decoration: underline;":"")+(c.Oj?"font-style: italic;":"")+(a.Bd?"cursor: pointer;":""));this.sa.push(c);this.ed=c;e="color: "+a.Tj.Nb();if(ln.Nh.rE)var f=c+"::-webkit-input-placeholder";else ln.Nh.NC?f=19>parseInt(ln.Nh.version)?c+":-moz-placeholder":c+"::-moz-placeholder":ln.Nh.Av&&(f=c+":-ms-input-placeholder");nn.T(f,e);"textArea"==a.qh?(e="","0"==b.lineHeight?e="normal":b.lineHeight&&(e="line-height:"+b.lineHeight+"px;"),this.ba='<textArea ondragstart="return false;" data-type="input-box" data-mid="'+
a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" placeholder="'+unescape(a.Ji)+'"style="'+e+'"></textArea>'):(e=(b=0<=["date","time"].indexOf(a.qh))?"value":"placeholder",f=unescape(a.Ji),b&&f&&a.Wa(f),this.ba='<input ondragstart="return false;" data-type="input-box" data-mid="'+a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" type="'+a.qh+'" '+e+'="'+f+'"/>')};rn.Ut=function(){return this.V().tagName};var sn=null;
rn.ky=function(){var a=document.getElementById("_AnalogInput"),b=document.getElementById("_AnalogArea"),c=pn.Na(0).V();a||(a=document.createElement("span"),a.style.zIndex="10",a.style.position="absolute",a.style.left="-9999px",a.id="_AnalogInput",c.appendChild(a));b||(b=document.createElement("textarea"),b.style.zIndex="10",b.style.position="absolute",b.style.left="-9999px",b.id="_AnalogArea",b.style.height="0",c.appendChild(b))};
rn.Mb=function(){qn.j.Mb.apply(this,arguments);this.V().addEventListener("change",this.ay.bind(this));this.V().addEventListener("input",this.tA.bind(this));this.V().addEventListener("focus",this.zy.bind(this));this.V().addEventListener("click",this.fy.bind(this));this.ky()};rn.Fs=function(){var a=this.c.w.param;return{importLimit:a.importLimit,limitCharset:a.limitCharset,lengthItem:a.lengthItem,lengthLimit:a.lengthLimit,lineHeight:a.inputLineheight}};
rn.vA=function(a){var b=this.V(),c=this.Fs(),d=b.value;if(!c.importLimit&&!c.lengthItem||"0"==c.importLimit&&"0"==c.lengthItem)a&&a(d);else{var e=!1,f=document.getElementById("_AnalogInput"),g=document.getElementById("_AnalogArea"),h=this.Ut();if(c.importLimit)switch(c.importLimit){case "1":var k=d.match(/[\u4e00-\u9fa5]/gi)||[],k=k.join("");k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u4e2d\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":k=d.match(/[a-z]/gi)||[];k=k.join("");
k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u82f1\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "4":if(c.limitCharset){k=c.limitCharset;c.limitCharset+="\n";for(var l=!1,m=0;m<d.length;)-1==c.limitCharset.indexOf(d[m])?(d=d.replace(d[m],""),l=!0):m++;l&&(Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u5982\u4e0b\u5b57\u7b26\uff1a\uff08"+k+"\uff09",null,function(){a&&a(d)}),e=!0)}}if(!e)if("INPUT"==h){if(d=d.replace(/\s/gi,"&nbsp;"),f.innerHTML=d,d=d.replace(/\&nbsp;/g," "),g=b.offsetWidth,
b=f.offsetWidth,c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b),f.innerHTML=d,Mugeda.messageBox("\u6700\u591a\u53ef\u4ee5\u8f93\u5165 "+b+" \u4e2a\u5b57\u7b26\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":if(b>g)for(c=0;c<d.length;c++)b>g&&(d=d.substring(0,d.length-1),f.innerHTML=d,b=f.offsetWidth,Mugeda.messageBox("\u8f93\u5165\u8d85\u51fa\u4e86\u5141\u8bb8\u7684\u957f\u5ea6\u8303\u56f4\u3002",null,function(){a&&
a(d)}),e=!0)}}else if("TEXTAREA"==h&&c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b));g.value=d;break;case "2":g.value=d,f=parseInt(window.getComputedStyle(b).lineHeight)||39,Math.round(g.scrollHeight/f)>=Math.round(b.scrollHeight/f)?g.value=sn:sn=d}!e&&a&&a(d)}};rn.tA=function(){};rn.fy=function(){var a=this.V();document.activeElement!=a&&a.focus()};
rn.zy=function(){var a=this.V(),b=this.Ut(),c=document.getElementById("_AnalogInput"),d=document.getElementById("_AnalogArea"),e=window.getComputedStyle(a);"INPUT"==b?(c.style.font=e.font,c.style.transform=e.transform,c.style.left="-9999px"):"TEXTAREA"==b&&(d.style.font=e.font,d.style.transform=e.transform,d.style.overflowY="hidden",d.style.width=a.offsetWidth+"px",d.style.padding=0,d.style.border="none",d.style.left="-9999px")};
rn.ay=function(){var a=this,b=a.V(),c=b.value;a.vA(function(d){c!=d&&(b.value=d,b.focus(),b.select());a.c.Wa(d)})};rn.s=function(){var a=this.V();if(document.activeElement==a){var b=a.getBoundingClientRect(),a=b.top,c=b.bottom,b=kn.sk(),a=(a+c)/2,b=b.height,c=this.c.Ua().R.Gf;if(0>a||a>b)c.style.cssText+=ln.prefix.f+"transform: translateY(-200px);"}};rn.ja=function(a,b,c){var d=this.c;qn.j.constructor.j.ja.apply(this,arguments);d=d.Ib();d!=this.da.value&&(this.da.value=d)};on.Wd(2031,qn);
})();